addons:
  sonarcloud:
    organization: "Majlanky"

cache:
  directories:
    - $HOME/.m2

language: java

jdk: openjdk8

install: true
script: chmod 777 mvnw && ./mvnw clean install sonar:sonar -P ITs -Dsonar.login=${SONAR_TOKEN}

after_success:
  - bash <(curl -s https://codecov.io/bash)